### Запрос всех сотрудников
GET http://localhost:8181/api/v1/employee

### Запрос сотрудника по идентификатору
GET http://localhost:8080/api/v1/employee?id=2002

### Запрос сотрудников по должности
GET http://localhost:8181/api/v1/employee?post=DIRECTOR

### Запрос сотрудников по должности
GET http://localhost:8181/api/v1/employee?post=DIRECTOR